### PR TITLE
Upgrade to Ext JS 6

### PR DESCRIPTION
**Pull request by Edvardoh**
packages to double check
- slate-core-data
- jarvus-griderrors

Also, something looks off with the panel headers, content seems to be positioned underneath the header in Ext panels.. after some digging I wasn't able to figure out the underlying cause

### CODE REVIEW

**Comment by themightychris** [comment]
@Edvardoh regarding the jarvus-griderrors package, you should insert a `debugger` statement at the top of every method it implements, search through the app code to see where those methods get called, figure out how to trigger them through the UI, and then step through them line by line and ensure that each operation and code path still seems to be working as expected. It looks like some private framework methods are used by it, so you may find that you need to figure out a new way to do some things, preferably with newly available public methods

**Comment by themightychris** [comment]
@Edvardoh slate-core-data is already being used with some ext-6 projects and should be fine since it only implements mostly models/stores and they're the most stable components across framework versions. Let me know if you encounter any potential issues with it though

**Comment by themightychris** [comment]
@Edvardoh please go through the app and thoroughly test it out, creating markdown checklists in this PR for any errors/warnings/problems you find and then solving the ones you can, and tagging me where things aren't clear

**Comment by Edvardoh** [comment]
**Problems to Address**
- [ ] main container positioned behind header toolbar
- [ ] lost left padding in grid rows in contacts panel
- [ ] some icons are different (add icons in contacts panel are grey instead of green, similar with treepanel icons)
- [ ] star icon doesn't turn yellow when marking a contact row as 'primary point'
- [ ] getting 404 errors when clicking/interacting with anything in the main header toolbar (edit profile, my drafts, search, etc.) - note: this happens on develop branch as well so I may have something configured wrong in my local instance?
- [ ] panel dividers/borders/masks are sitting in front of main header toolbar (z index issue?)
- [ ] ext panel toolbar font is bolder
- [ ] main header toolbar has extra left and right padding

**Comment by Edvardoh** [comment]
@themightychris Please see the final item in the checklist above. I'm also having this problem on the main branch, so it's not because of the upgrade. Might just have something mixed up on my local install. Following those links should work even on a local instance right?

**Comment by themightychris** [comment]
Merged into `slate` repository

**Pull request closed without merging**
